In [5]:
import pandas as pd 
import seaborn as sns

In [6]:
house_prices = pd.read_csv("HousePricePrediction.csv")

In [7]:
house_prices

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [8]:
house_prices.shape
house_prices.describe()
house_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [9]:
house_prices.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [10]:
house_prices.drop(['Id'], axis=1, inplace=True)


house_prices["SalePrice"] = house_prices["SalePrice"].fillna(
    house_prices["SalePrice"].mean()
)

house_prices.dropna(inplace = True)

print(house_prices.isnull().sum())

house_prices.head()

MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [11]:
house_prices

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [12]:
# Data Preprocessing - Encoding 
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
house_prices = pd.get_dummies(house_prices, columns=cols, drop_first=True)

In [13]:
house_prices.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,False,False,...,False,False,False,False,False,False,False,True,False,False
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,False,False,...,False,False,False,True,False,False,False,False,False,False
2,60,11250,5,2001,2002,0.0,920.0,223500.0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,70,9550,5,1915,1970,0.0,756.0,140000.0,False,False,...,False,False,False,False,False,False,False,False,True,False
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,False,False,...,False,False,False,False,False,False,False,True,False,False

In [14]:
#Train Test split
from sklearn.model_selection import train_test_split

x = house_prices.drop(["SalePrice"], axis = 1)
y = house_prices["SalePrice"]

x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size= 0.2, random_state= 42
)

In [15]:
x_test.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
178,20,17423,5,2008,2009,0.0,2216.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
678,20,11844,5,2008,2008,0.0,2046.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2878,50,10164,5,1939,1950,0.0,992.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2691,20,7733,5,2005,2005,0.0,1142.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1898,30,8574,8,1916,2000,0.0,816.0,False,False,True,...,False,False,False,False,False,False,True,False,False,False

In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [18]:
y_pred = model.predict(x_test)

In [19]:
y_pred

array([252718.49490862, 234472.9809095 , 156972.71874701, 192468.84764739,
       173928.35155496, 212155.14398261, 130765.3798881 , 163103.24545777,
       224773.41449334, 162367.59694669, 200021.01600619, 175574.34803764,
       161693.24430235, 206329.51248517, 173922.25036446, 196796.49427305,
       185939.50160841, 176495.12579278, 154757.55575672, 165428.39929839,
       173818.57762967, 187161.12218114, 199696.62165524, 186696.98758751,
       209609.39229537, 146701.08939592, 219354.78043781, 151172.83331042,
       171813.96709675, 171081.87143923, 215196.71043635, 139946.18173416,
       226427.93943849, 181815.81553321, 133476.27761001, 204031.52582001,
       165764.76856362, 166681.48714581, 148986.78889559, 165241.82852711,
       228615.56571778, 192197.13410196, 205457.14673759, 211789.53421061,
       200594.68905778, 265407.46997553, 186047.89283702, 207793.34939867,
       225535.05242531, 154806.72521173, 228581.77631186, 149584.81375637,
       203992.04436097, 142794.39941645, 185142.69531412, 178713.89562625,
       139285.38003114, 204975.81267348, 189142.3510827 , 200262.21887318,
       176279.86155988, 206841.62354074, 216025.42300271, 118095.27104824,
       156439.65111274, 169598.66995845, 155342.36105855, 197791.83424903,
       173841.80064597, 203402.47694395, 200923.70591627, 211847.7835939 ,
       202027.86862594, 170404.12649561, 198889.66043675, 195440.81043257,
       189854.55176946, 158025.53658466, 221417.81779894, 171622.80365608,
       157883.46742298, 171992.17586116, 159368.549714  , 146785.67003038,
       167684.95566607, 231652.18098487, 210565.4092739 , 214256.81300211,
       159201.46196391, 211013.62216327, 196842.60297143, 152790.67590949,
       150108.80538054, 197813.36812198, 177477.13891708, 229088.35819082,
       178105.11988917, 175090.07843637, 211268.88714775, 167623.04005815,
       186469.81552278, 168551.38329841, 176219.01493707, 152259.83091972,
       226113.85629702, 165181.37274022, 166827.51012675, 104837.89629509,
       135576.7231555 , 129810.02523091, 199494.84842995, 164480.60414408,
       199400.0249005 , 138433.62987807, 225948.45079756, 170300.89786261,
       206162.06458757, 159412.27850582, 200460.71372919, 200631.74134641,
       180620.17742648, 149959.64736716, 163093.5216864 , 176219.01493707,
       166500.74713574, 178876.92147151, 176802.32922691, 195966.47989927,
       198586.40559451, 197097.0395566 , 206489.74885826, 199316.48267768,
       203756.12173563, 219702.54763025, 136545.61739629, 166209.98053138,
       198405.99231367, 195960.59007357, 199023.90237263, 174469.08100588,
       215111.04313665, 155248.57069367, 160973.35149032, 192511.93227898,
       158431.67290237, 165823.31105416, 213900.49698133, 195269.33570139,
       165537.19109672, 213559.32965903, 103757.18672796, 197588.54938807,
       189207.68938787, 153195.20661016, 166635.12743809, 195454.77152995,
       188457.5780082 , 213295.74902066, 191828.48505655, 194581.98823074,
       189391.98348953, 204318.63296082, 257912.58379662, 164621.43013808,
       199137.94609048, 213159.26309789, 172300.61484409, 219530.39466267,
       176690.00863499, 187856.78147155, 210787.15639771, 190927.28018534,
       140833.34273087, 158799.05546201, 177609.63549662, 188934.20683406,
       212512.2646025 , 187760.1151559 , 156406.55460538, 190504.04997581,
       197059.27065322, 139034.40984877, 216766.31892871, 144534.87735824,
       178456.67447266, 114110.38335856, 158265.30620752, 168087.95560217,
       158748.52762071, 201873.20888325, 251286.20573853, 206861.95894432,
       210195.67986615, 178260.26766121, 149589.11444471, 208577.65735176,
       154092.41550519, 170461.06983626, 179744.17002743, 232405.54300403,
       144836.21494842, 184635.56298479, 220673.58455096, 167336.77050672,
       166357.53710233, 218535.12537614, 207317.60885711, 161743.84188678,
       144338.48758258, 129966.04831926, 218038.0982094 , 136952.16041275,
       114371.58609954, 163472.46569492, 197665.76940988, 131636.26326339,
       201812.82425305, 209533.28539163, 156491.5698645 , 225742.55968696,
       199659.03369425, 199958.50352672, 107089.42740863, 164813.48994686,
       185571.66460076, 195634.82408078, 176209.55623416, 174826.71361444,
       169421.34698396, 158558.78371443, 149359.22439723, 185957.52702353,
       168425.58439022, 151954.56731205, 252853.84150201, 150471.6050286 ,
       194114.61808713, 144746.91546123, 140005.65129716, 133403.13884608,
       180717.41742518, 146569.05826924, 128774.87956671, 185145.38941373,
       154069.30703135, 149391.51497473, 172509.32606893, 170090.86205473,
       197445.93160522, 184243.46117939, 181031.18168503, 191490.74694908,
       177769.88515802, 179466.7140124 , 174804.8160821 , 148855.783822  ,
       188200.86192085, 147039.22430078, 180495.44222624, 155010.12785847,
       188946.21387426, 215075.34327892, 199567.10166778, 193783.91989819,
       173159.36425453, 220208.37694269, 222632.6443224 , 196125.39874418,
       210445.86626222, 164254.06505514, 186746.29296234, 174841.46506001,
       180275.56348681, 218839.72746599, 114371.58609954, 165839.22794681,
       210488.99487662, 181330.37215036, 137331.72838049, 233899.69683796,
       181143.66812107, 165256.11975745, 196194.09421475, 167115.94607202,
       181364.92614335, 163164.0239565 , 247018.84749868, 241028.1912732 ,
       191318.8978882 , 181456.12949052, 197791.73398145, 209291.65463925,
       169085.47674731, 164433.38033128, 217428.82755744, 210393.13475633,
       207549.69856369, 191691.76980751, 198083.93745904, 216055.50502722,
       142463.34079018, 194459.96774539, 168461.35534827, 144591.90967471,
       153551.20746546, 176679.1577214 , 206769.10109411, 181891.88394756,
       180299.05062613, 184100.71547998, 151915.30632184, 143167.66961371,
       215999.99052122, 127076.67724992, 197252.25846896, 194204.93488174,
       163095.25720605, 148094.05861606, 184248.90186689, 154012.93154969,
       178900.68094493, 149722.44620514, 159050.14718569, 159376.38259829,
       235420.4856382 , 153061.75228055, 193004.37986398, 183726.86286784,
       124257.6543289 , 161399.25867094, 184269.60722418, 166156.95924158,
       153813.82514406, 146265.20443356, 143990.35367608, 160783.12132054,
       151026.40085159, 208333.68330063, 169082.48843212, 178414.30553118,
       216252.88725618, 146982.77284297, 184973.30172597, 193960.58294309,
       181018.68084839, 213062.11789907, 232809.38954367, 160601.9044889 ,
       180307.76128556, 199512.14920763, 208973.44653792, 107292.23740414,
       144445.86352591, 146593.96194727, 199116.98715707, 170886.95468691,
       161269.87949464, 155605.38307668, 149803.54528149, 189742.87499755,
       160140.75185406, 183997.37513417, 181827.13580214, 169506.03818208,
       190446.50266082, 166110.20975986, 181112.48212793, 192529.37530846,
       180829.55019633, 116733.94725674, 148677.58811143, 200859.1299849 ,
       183607.95933619, 191324.05579817, 188467.79976968, 170402.61823776,
       155812.80807251, 262588.20878397, 198161.99802712, 181850.43114157,
       101430.10831307, 196095.9064516 , 153563.35859994, 169058.95196399,
       178093.37933468, 110770.50767727, 222370.42369105, 210192.20006704,
       189980.7631204 , 116198.5589669 , 164392.48746452, 169730.05540829,
       142008.48185647, 214030.45490328, 207078.93658283, 235481.89514602,
       163290.13484648, 177036.33144289, 160484.61610153, 212619.9856155 ,
       134515.43479773, 200797.06211978, 187224.32472649, 132704.67403362,
       185921.61075679, 157524.02550765, 170750.8281156 , 163715.35505077,
       194280.313614  , 135967.23890201, 173263.72195225, 195651.9204945 ,
       177543.0884333 , 198677.3205201 , 156327.48487994, 161122.78483503,
       147204.7104659 , 186615.8098938 , 151882.57857565, 211429.23311854,
       161445.75036235, 268508.99991143, 177026.81757036, 214012.2302411 ,
       200271.67842193, 198427.01875727, 182249.69675051, 203777.99674603,
       215703.25408296, 154314.33393278, 173100.48077952, 234241.12458676,
       225552.59115637, 195222.6504956 , 173897.44204678, 189115.32730588,
       191800.79017214, 133802.06992342, 200493.60663905, 154774.25187515,
       115309.67014768, 194882.70400584, 155952.81623274, 233880.36681515,
       163131.33463037, 199794.46288928, 193670.64336339, 179942.53653265,
       197807.06769087, 172628.59221283, 170033.58494542, 235114.48330739,
       188332.94866519, 173409.33352922, 174823.2435545 , 173274.00256198,
       149339.49009033, 183491.54476424, 190985.22332398, 166323.21365383,
       270704.83545143, 200082.59705839, 202341.34200258, 176713.62818367,
       130498.34801111, 203950.20370376, 202865.94563848, 227286.45753821,
       229051.9939439 , 182978.66683876, 168202.52394176, 172342.19804808,
       171552.47962346, 232123.11911111, 193044.40231262, 146677.67030663,
       216584.07423251, 180229.68049119, 177947.4154363 , 182337.32947211,
       170008.86156822, 155349.32712309, 196950.10882564, 209658.9844436 ,
       187942.86424434, 220753.34606842, 188821.59980041, 403521.90446224,
       161626.80238796, 174270.24264478, 208345.57199228, 204719.91289229,
       163788.14604768, 203979.00053353, 152942.5163348 , 152556.02903603,
       221483.50491693, 129150.96156267, 176690.9354842 , 203256.39174207,
       201637.26177934, 165125.42269127, 157593.35887447, 233628.05943223,
       186850.39429681, 174074.80608174, 153027.71624749, 197784.90237422,
       187258.31796397, 168792.95816059, 138263.08151985, 179548.74353006,
       205327.26318314, 200401.6517463 ,  97729.08993345, 157481.59489184,
       217345.61217667, 221615.8661885 , 164294.21575809, 187631.16869195,
       196550.83010785, 189945.25689464, 240411.48789023, 218150.17232396,
       198065.18403918, 202616.17568567, 155009.55721099, 143694.05089015,
       157424.06172402, 190451.99794296, 189211.3514294 , 179186.37917117,
       197569.27489621, 166715.73479746, 162394.60910155, 175594.10948205,
       219350.09703344, 166169.21155391, 154629.16508755, 196753.53450955,
       145240.94312435, 200374.57979332, 165408.57366889, 179634.67606189,
       128365.7029456 , 203340.24810754, 169349.43877538, 159409.2608855 ,
       194879.19210508, 176803.94056331, 180989.62813455, 132855.73730372,
       189778.08937143, 184409.68368399, 192924.51753155, 181332.90582177,
       216010.14796655, 213164.99422859, 178024.17323454, 156504.6463558 ,
       151329.46197714, 190690.53295963, 141849.36897367, 151595.40914274,
       186315.07722641, 170331.40867543, 199374.49849514, 165823.31105416,
       165423.90551415, 150001.15419577, 162074.65330947, 147028.10662733,
       205240.39506079, 175377.6462581 , 115090.37177047, 186681.8777885 ,
       202241.69533154, 230823.19166716, 147597.14866632, 196752.1020599 ,
       201019.88446766, 196247.69676838, 163454.80970007])

In [21]:
# Evaluate 
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(f"R^2 Score: {r2}")

n = x_test.shape[0]
p = x_test.shape[1]

adjusted_r2 =  1 - ((1-r2)*(n-1)/ (n-p-1))
print("adjusted r^2:", adjusted_r2)

R^2 Score: 0.3469223785187572
adjusted r^2: 0.307666346626442